# Generated by Django 5.0 on 2024-01-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_complete",
            field=models.BooleanField(default=False),
        ),
    ]
