# Generated by Django 5.0.2 on 2024-02-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_profile_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_cuvalles",
            field=models.BooleanField(default=False),
        ),
    ]
