# Generated by Django 5.0 on 2024-01-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_group_task_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="limit_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
