# Generated by Django 5.0 on 2024-01-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
        ("timetable", "0004_remove_subject_clave_remove_subject_crn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.subject",
            ),
        ),
    ]
