# Generated by Django 5.0 on 2024-02-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardgroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
