# Generated by Django 5.0.3 on 2024-03-27 07:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("teacher", models.CharField(max_length=50)),
                ("clasroom", models.CharField(max_length=50)),
                (
                    "hour_start",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_hour_format",
                                message="Hour should be in the format HH:MM",
                                regex="^\\d{2}:\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "hour_end",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_hour_format",
                                message="Hour should be in the format HH:MM",
                                regex="^\\d{2}:\\d{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Lunes", "Lunes"),
                            ("Martes", "Martes"),
                            ("Miercoles", "Miercoles"),
                            ("Jueves", "Jueves"),
                            ("Viernes", "Viernes"),
                            ("Sabado", "Sabado"),
                        ],
                        default="Lunes",
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF0000", "Rojo"),
                            ("#FF7F00", "Naranja"),
                            ("#FFFF00", "Amarillo"),
                            ("#00FF00", "Verde"),
                            ("#0000FF", "Azul"),
                            ("#4B0082", "Indigo"),
                            ("#8F00FF", "Violeta"),
                        ],
                        default="#FF0000",
                        max_length=7,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
