# Generated by Django 5.0 on 2024-01-15 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=10)),
                ("crn", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=50)),
                ("teacher", models.CharField(max_length=50)),
                ("clasroom", models.CharField(max_length=50)),
                ("hour_start", models.CharField(max_length=50)),
                ("hour_end", models.CharField(max_length=50)),
                ("day", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF0000", "Red"),
                            ("#FF7F00", "Orange"),
                            ("#FFFF00", "Yellow"),
                            ("#00FF00", "Green"),
                            ("#0000FF", "Blue"),
                            ("#4B0082", "Indigo"),
                            ("#8F00FF", "Violet"),
                        ],
                        default="#FF0000",
                        max_length=7,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
