# Generated by Django 5.0 on 2024-01-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="color",
            field=models.CharField(
                choices=[
                    ("#FF0000", "Rojo"),
                    ("#FF7F00", "Naranja"),
                    ("#FFFF00", "Amarillo"),
                    ("#00FF00", "Verde"),
                    ("#0000FF", "Azul"),
                    ("#4B0082", "Indigo"),
                    ("#8F00FF", "Violeta"),
                ],
                default="#FF0000",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="day",
            field=models.CharField(
                choices=[
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miercoles", "Miercoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sabado", "Sabado"),
                ],
                default="Lunes",
                max_length=10,
            ),
        ),
    ]
