# Generated by Django 5.0 on 2024-01-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0002_alter_subject_color_alter_subject_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="hour_end",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="subject",
            name="hour_start",
            field=models.IntegerField(),
        ),
    ]
