# Generated by Django 5.0 on 2024-01-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0003_alter_subject_hour_end_alter_subject_hour_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="clave",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="crn",
        ),
        migrations.AlterField(
            model_name="subject",
            name="hour_end",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="subject",
            name="hour_start",
            field=models.TimeField(),
        ),
    ]
