# Generated by Django 5.0.3 on 2024-03-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0004_remove_subject_clave_remove_subject_crn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="hour_end",
            field=models.TimeField(default="23:59:59"),
        ),
    ]
