# Generated by Django 5.0.3 on 2024-03-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0005_alter_subject_hour_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="hour_end",
            field=models.TimeField(),
        ),
    ]
