# Generated by Django 5.0.3 on 2024-03-27 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0007_alter_subject_hour_end_alter_subject_hour_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="hour_end",
            field=models.CharField(
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_hour_format",
                        message="Hour should be in the format HH:MM",
                        regex="^\\d{2}:\\d{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="hour_start",
            field=models.CharField(
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_hour_format",
                        message="Hour should be in the format HH:MM",
                        regex="^\\d{2}:\\d{2}$",
                    )
                ],
            ),
        ),
    ]
