# Generated by Django 5.0 on 2024-01-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Remainder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("is_important", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
    ]
