# Generated by Django 5.0 on 2024-01-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
